environment:
  ELECTRON_RUN_AS_NODE: 1
  VSCODE_BUILD_VERBOSE: true

branches:
  only:
  - master
  - develop

cache:
  - '%LOCALAPPDATA%\Yarn\cache'

install:
  - ps: Install-Product node 8.9.1 x64

build_script:
  - yarn

test_script:
  - node --version